### PR TITLE
Publish minutes of 2021-07-22 meeting

### PR DESCRIPTION
**Pull request by Rob--W**
Generated from https://docs.google.com/document/d/1QkwhEMtMS67JBUkl_WVPZ4lRSKoWcQNlLJSf_GwSXg8/edit

Using a process similar to #23.

During this meeting, we discussed or mentioned #13, #30, #36, and agreed to file new issues (about tracking work on manifest file (TBD) and participating in TPAC at #45).

### CODE REVIEW

**Comment by Rob--W** [comment]
So far I used the PDT timezone as the primary point of reference (with UTC and time zone converters). Should we continue to do that in this way, or should we start using UTC instead? If we use UTC, then the document should be attributed to `2021-07-23` instead of `2021-07-22`.

**Comment by mukul-p** [comment]
> So far I used the PDT timezone as the primary point of reference (with UTC and time zone converters). Should we continue to do that in this way, or should we start using UTC instead? If we use UTC, then the document should be attributed to `2021-07-23` instead of `2021-07-22`.

UTC would be better choice. We can check what is the precedent.

**Comment by dotproto** [comment]
As I recall, when we last discussed time zones we decided to use Pacific time because the browser member reps either worked in or worked closely with people in that time zone. Targeting the Pacific time zone allowed us to set a single time (8 AM Pacific) without regard for [daylight savings time](https://en.wikipedia.org/wiki/Daylight_saving_time). 

If we were to use UTC, we would need to decide how to handle daylight savings: do we keep maintain a fixed UTC time or adjust the meeting to accommodate daylight savings? If so, what DST region do we accommodate (observation dates vary by location)?

**Comment by Rob--W** [comment]
I'm fine with using PDT as a reference (since we based our meeting schedule on it, and conversions to other time zones are provided in the schedule and meeting notes).

@mukul-p Any objections?

**Comment by dotproto** [comment]
Ah, I was thinking more about how we schedule rather than canonical datetime references. My personal preference would be to schedule around Pacific but for fixed dates and times to use UTC. @xeenon, do you have any thoughts?

**Review by dotproto — APPROVED** [review]
LGTM. I'm good with either holding off on this merge until we resolve the UTC question or accepting it as is and updating the timestamp later if necessary.

**Pull request merged**
