### PR TITLE
Document How we work

### LINKED ISSUE #29: Update contributing guide with info on current communication channels
Per [this discussion](https://github.com/w3c/webextensions/issues/13#issuecomment-864177738) in #13, we should expand the [contributing guide](https://github.com/w3c/webextensions/blob/main/CONTRIBUTING.md) to include more specific details on how we use our communication channels and our [meeting schedule](https://www.w3.org/community/webextensions/2021/06/18/wecg-public-meeting-schedule/).

> - Issues for specific topic and long-running conversations.
> - Conference calls to discuss topics that require higher bandwidth conversations than issues typically allow
> - Matrix for general chat, quick questions, pings, etc. We may ask participants to open issues here for tracking purposes.

### PR DESCRIPTION
**Pull request by Rob--W**
Fixes #29.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Such a big improvement 🙌 

Should we add a link to this in the README or even considering moving some of it there? I think a lot of this is key information that it would be nice to make as visible as possible.

**Review by xeenon — APPROVED** [review]

**Comment by Rob--W** [comment]
> Such a big improvement 🙌
> 
> Should we add a link to this in the README or even considering moving some of it there? I think a lot of this is key information that it would be nice to make as visible as possible.

What is the "link to his"? I've already put a link to CONTRIBUTING.md in the README.

**Comment by oliverdunk** [comment]
> > Such a big improvement 🙌
> > Should we add a link to this in the README or even considering moving some of it there? I think a lot of this is key information that it would be nice to make as visible as possible.
> 
> What is the "link to his"? I've already put a link to CONTRIBUTING.md in the README.

I think I totally missed that the first time, sorry. I do think it'd be nice to just pull some of this information in to the README directly but definitely not a blocker for this PR.

**Review by dotproto — APPROVED** [review]
Thanks for doing this, @Rob--W!

**Pull request merged**
