### PR TITLE
Expand the API proposal to include a "behavior" section

### PR DESCRIPTION
**Pull request by rdcronin**
The behavior of certain APIs may not be immediately clear from the
API schema. Add a separate section for "behavior" to allow authors
to specify notes related to the behavior of the API if they are non-
obvious.

### CODE REVIEW

**Comment by rdcronin** [comment]
@Rob--W Please review -- let me know if this looks good to you, and I'll tag in a couple other folks.

I don't want to be _too_ prescriptive in this section, but I do think it's worth having as part of the default proposal.

**Review by Rob--W — APPROVED** [review]

**Review by xeenon — APPROVED** [review]

**Comment by rdcronin** [comment]
Thanks, Rob and Timothy!

@dotproto and @oliverdunk , please also review.

If it looks good to you, please merge.

**Review by dotproto — APPROVED** [review]
LGTM

**Review by oliverdunk — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
