### PR TITLE
Create behaviors-in-packed-extensions.md

### PR DESCRIPTION
**Pull request by hanguokai**
Add a new memo about differences between packed and unpacked extensions.

### CODE REVIEW

**Review by Rob--W — CHANGES_REQUESTED** [review]
I think that this note belongs to Chrome's developer documentation, not in the WECG.

Side note: In Firefox, the testing APIs of declarativeNetRequest are not guarded on developer mode, but a specific preference. The thought behind that is that if someone runs into issues with their extension, that they can visit `about:config` to toggle the preference to get better diagnostic information, independently of other behavioral changes tied to the installation mode. This is documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest#testing.

**Comment by hanguokai** [comment]
@oliverdunk @patrickkettner Would you like to create a new article about this difference at https://developer.chrome.com/ ? If yes, I will close this PR.

**Comment by Rob--W** [comment]
Closing since this does not belong to the WECG.

Chrome developer documentation issues can be filed at https://issuetracker.google.com/issues/new?component=1400036&template=1897236

Before filing, check whether there is already an issue filed. You can see them at https://issuetracker.google.com/issues?q=status:open%20componentid:1400036&s=created_time:desc

**Comment by patrickkettner** [comment]
@hanguokai makes sense to me! Would you be able to file via the links rob shared?

**Comment by hanguokai** [comment]
@patrickkettner Done. This is the issue link for Chrome document https://issuetracker.google.com/issues/345627612

**Pull request closed without merging**
