### PR TITLE
Publish minutes of 2022-09-01 meeting

### PR DESCRIPTION
**Pull request by Rob--W**
Generated from https://docs.google.com/document/d/1QkwhEMtMS67JBUkl_WVPZ4lRSKoWcQNlLJSf_GwSXg8/edit using the tool and process from https://github.com/w3c/webextensions/pull/105.

During this meeting we discussed or mentioned #260, #261, #262, #263, #264, #267, #244, #232, #242, #162.

I've also fixed some timezone references (PST -> PDT). Unfortunately, the everytimezone links were also off-by-one for many months, but they should be good now.

### CODE REVIEW

**Comment by hanguokai** [comment]
Was #258 discussed at this meeting?

I don't see #252 discussed at this meeting. Why @carlosjeurissen added label `accepted: chrome` and `accepted: firefox` on it?

I see chrome and safari don't opposed to #267 . Why @Rob--W added label `rejected: chrome` and `rejected: safari` on it?

**Comment by carlosjeurissen** [comment]
@hanguokai Thanks for closely following the meeting notes and processes in the group.

#252 was discussed in the previous meeting (Aug 4, 2022), in which Chrome and Safari expressed being in favour.

As for #267, neutral tags might also work here. @xeenon proposed to be able to tag issues with a neutral `no-objections` tag. See: https://github.com/w3c/webextensions/issues/244#issuecomment-1234680010

**Comment by Rob--W** [comment]
> Was #258 discussed at this meeting?

It wasn't part of the agenda, so it wasn't covered. I don't know if omission from the agenda by @xeenon was intentional.

> I don't see #252 discussed at this meeting. Why @carlosjeurissen added label `accepted: chrome` and `accepted: firefox` on it?

This was dicussed during the previous meeting. Notes from that meeting are at
https://github.com/w3c/webextensions/blob/main/_minutes/2022-08-04-wecg.md

The labels were recently added because they are new, see #244 for details on labels. 

> I see chrome and safari don't opposed to #267 . Why @Rob--W added label `rejected: chrome` and `rejected: safari` on it?

The "Resolution" comment in the meeting notes was added after we all reached consensus on closing the issue.

**Comment by hanguokai** [comment]
> The "Resolution" comment in the meeting notes was added after we all reached consensus on closing the issue.

Closing it is OK. But I'm talking about labels here, you could close it without "reject" labels.

> This was dicussed during the previous meeting. Notes from that meeting are at
> https://github.com/w3c/webextensions/blob/main/_minutes/2022-08-04-wecg.md
> #252 was discussed in the previous meeting (Aug 4, 2022), in which Chrome and Safari expressed being in favour.

In 2022-08-04-wecg.md, about #252 , 

> "[simeon] From my perspective, a Chrome issue would be welcome."

Like millions of other Chromium issues, I think this sentence means this is a beginning and does not mean acceptance.

In today meeting note, about #267 , 

> "[simeon] In general in favor of making developers lifes easier. No strong objections, but in terms of relative priority this feels like something as an Available issue."

I think this likes above sentence, that means you can add an issue too, but will not implement soon.

> As for #267, neutral tags might also work here. @xeenon proposed to be able to tag issues with a neutral no-objections tag. See: #244 (comment)

This is better than "accept" or "reject". I understand, from browser venders point of view, there are still a lot of important issues that remain unresolved. Therefore, it is often difficult to say whether it will be implemented or when it will be implemented.

**Comment by Rob--W** [comment]
> > This was dicussed during the previous meeting. Notes from that meeting are at
> > https://github.com/w3c/webextensions/blob/main/_minutes/2022-08-04-wecg.md
> > #252 was discussed in the previous meeting (Aug 4, 2022), in which Chrome and Safari expressed being in favour.
> 
> In 2022-08-04-wecg.md, about #252 ,
> 
> > "[simeon] From my perspective, a Chrome issue would be welcome."
> 
> Like millions of other Chromium issues, I think this sentence means this is a beginning and does not mean acceptance.

We've just renamed "accepted" to "supportive" to more closely match what we're intending.

> > The "Resolution" comment in the meeting notes was added after we all reached consensus on closing the issue.
> 
> Closing it is OK. But I'm talking about labels here, you could close it without "reject" labels.

In a similar vein, we've renamed "rejected" to the less strongly worded "opposed".

> In today meeting note, about #267 ,
> 
> > "[simeon] In general in favor of making developers lifes easier. No strong objections, but in terms of relative priority this feels like something as an Available issue."
> 
> I think this likes above sentence, that means you can add an issue too, but will not implement soon.

The meeting notes reflect what has been said in the meeting. Because it is a discussion, viewpoints can change after having expressed and processed the initial statements. In this specific example, we were initially indifferent/neutral, but after weighing the options we decided to oppose the feature request (elaborated in #267).

**Comment by dotproto** [comment]
Most of the discussion on this issue seems to be about how labels have been applied to issues rather than the minutes themselves. As such, I think it may be best to (1) move discussion of the labels themselves to issue #244 and (2) move discussion of a whether given label was correctly applied to that issue's comments.

**Review by xeenon — APPROVED** [review]

**Pull request merged**
